package Main;

import Object.Chest;
import Object.Entrance_Exit;
import Object.House;
import Object.Sign;

public class objectHandler {
    The_Hub hb;
    public objectHandler(The_Hub hb) {
        this.hb=hb;
    }
    public void setObject() {
        hb.obj[0]=new Sign(hb, "HELLO");
        hb.obj[0].worldX=hb.maxWorldWidth/2+2*hb.resTileSize;
        hb.obj[0].worldY=hb.maxWorldHeight/2-300;
        hb.obj[0].locationX=1;
        hb.obj[0].locationY=2;
        hb.obj[1]=new Chest(hb);
        hb.obj[1].worldX=hb.maxWorldWidth/2;
        hb.obj[1].worldY=hb.maxWorldHeight/2;
        hb.obj[1].locationX=0;
        hb.obj[1].locationY=3;
        hb.obj[2]=new Sign(hb, "NOPE");
        hb.obj[2].worldX=hb.maxWorldWidth/2+4*hb.resTileSize;
        hb.obj[2].worldY=hb.maxWorldHeight/2;
        hb.obj[2].locationX=2;
        hb.obj[2].locationY=2;
        hb.obj[3]=new Sign(hb, "YUP");
        hb.obj[3].worldX=hb.maxWorldWidth/2+2*hb.resTileSize;
        hb.obj[3].worldY=hb.maxWorldHeight/2;
        hb.obj[3].locationX=0;
        hb.obj[3].locationY=2;
        hb.obj[4]=new House(hb);
        hb.obj[4].locationX=1;
        hb.obj[4].locationY=4;
        hb.obj[4].worldX=hb.maxWorldWidth/2+hb.resTileSize;
        hb.obj[4].worldY=hb.maxWorldHeight/2;
        hb.obj[19]=new House(hb);
        hb.obj[19].locationX=1;
        hb.obj[19].locationY=4;
        hb.obj[19].worldX=hb.maxWorldWidth/2+4*hb.resTileSize;
        hb.obj[19].worldY=hb.maxWorldHeight/2;
        hb.obj[20]=new House(hb);
        hb.obj[20].locationX=1;
        hb.obj[20].locationY=4;
        hb.obj[20].worldX=hb.maxWorldWidth/2+7*hb.resTileSize;
        hb.obj[20].worldY=hb.maxWorldHeight/2;
        hb.obj[5]=new Entrance_Exit(hb, "one");
        hb.Exits[0]=hb.obj[5];//save exits to another array for later
        hb.obj[5].locationX=1;
        hb.obj[5].locationY=0;
        hb.obj[5].worldX=hb.maxWorldWidth/2;
        hb.obj[5].worldY=350;
        hb.obj[6]=new Entrance_Exit(hb, "one");
        hb.Exits[1]=hb.obj[6];
        hb.obj[6].locationX=1;
        hb.obj[6].locationY=1;
        hb.obj[6].worldX=hb.maxWorldWidth/2-60;
        hb.obj[6].worldY=1400;
        hb.obj[7]=new Entrance_Exit(hb, "path");
        hb.Exits[2]=hb.obj[7];
        hb.obj[7].worldX=hb.maxWorldWidth/2-30;
        hb.obj[7].worldY=350;
        hb.obj[7].locationX=1;
        hb.obj[7].locationY=1;
        hb.obj[8]=new Entrance_Exit(hb, "path");
        hb.Exits[3]=hb.obj[8];
        hb.obj[8].worldX=hb.maxWorldWidth/2+190;
        hb.obj[8].worldY=1100;
        hb.obj[8].locationX=1;
        hb.obj[8].locationY=2;
        hb.obj[9]=new Entrance_Exit(hb, "nope");
        hb.Exits[4]=hb.obj[9];
        hb.obj[9].worldX=1080;
        hb.obj[9].worldY=1488/2;
        hb.obj[9].locationX=1;
        hb.obj[9].locationY=2;
        hb.obj[10]=new Entrance_Exit(hb, "nope");
        hb.Exits[5]=hb.obj[10];
        hb.obj[10].worldX=530;
        hb.obj[10].worldY=912/2;
        hb.obj[10].locationX=2;
        hb.obj[10].locationY=2;
        hb.obj[11]=new Entrance_Exit(hb, "yup");
        hb.Exits[6]=hb.obj[11];
        hb.obj[11].worldX=210;
        hb.obj[11].worldY=1488/2;
        hb.obj[11].locationX=1;
        hb.obj[11].locationY=2;
        hb.obj[12]=new Entrance_Exit(hb, "yup");
        hb.Exits[7]=hb.obj[12];
        hb.obj[12].worldX=1096;
        hb.obj[12].worldY=912/2;
        hb.obj[12].locationX=0;
        hb.obj[12].locationY=2;
        hb.obj[13]=new Entrance_Exit(hb, "forest");
        hb.Exits[8]=hb.obj[13];
        hb.obj[13].worldX=1584/2;
        hb.obj[13].worldY=350;
        hb.obj[13].locationX=1;
        hb.obj[13].locationY=2;
        hb.obj[14]=new Entrance_Exit(hb, "forest");
        hb.Exits[9]=hb.obj[14];
        hb.obj[14].worldX=3168/2;
        hb.obj[14].worldY=1568;
        hb.obj[14].locationX=1;
        hb.obj[14].locationY=3;
        hb.obj[15]=new Entrance_Exit(hb, "forestTreasure");
        hb.Exits[10]=hb.obj[15];
        hb.obj[15].worldX=450;
        hb.obj[15].worldY=1100;
        hb.obj[15].locationX=1;
        hb.obj[15].locationY=3;
        hb.obj[16]=new Entrance_Exit(hb, "forestTreasure");
        hb.Exits[11]=hb.obj[16];
        hb.obj[16].worldX=760;
        hb.obj[16].worldY=455;
        hb.obj[16].locationX=0;
        hb.obj[16].locationY=3;
        hb.obj[17]=new Entrance_Exit(hb, "Village");
        hb.Exits[12]=hb.obj[17];
        hb.obj[17].worldX=2640;
        hb.obj[17].worldY=350;
        hb.obj[17].locationX=1;
        hb.obj[17].locationY=3;
        hb.obj[18]=new Entrance_Exit(hb, "Village");
        hb.Exits[13]=hb.obj[18];
        hb.obj[18].worldX=982;
        hb.obj[18].worldY=370;
        hb.obj[18].locationX=1;
        hb.obj[18].locationY=4;
    }
}
